name: frontend-build

on:
  push:
    branches: [ "main", "master" ]
    paths: ['frontend/**']
  pull_request:
    branches: [ "main", "master" ]
    paths: ['frontend/**']
  workflow_call:  # allows you to call this workflow from other ones

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Install Yarn version from .yarnrc.yml
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 23.1.0
      - run: cd frontend && yarn install
      - run: cd frontend && yarn build
      # - run: cd frontend && yarn test
